config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :image, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    validates :first_name, presence: true, length: {maximum: 40}
    validates :last_name, presence: true, length: {maximum: 40}
    validates :email, presence: true, length: {maximum: 200},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
    @users = User.all
  end
  def show
  end
  def new
    @post = Post.new
  end
  def confirm
    @post = Post.new(feed_params)
  end
  def edit
  end
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:image, :image_cache, :content, :user_id)
  end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path(user.id)
    else
      flash.now[:danger] = 'Login failed'
      render 'new'
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'You logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end
  def show
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :password, :password_comfirm, :dob, :sex)
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebookclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <nav class="navbar navbar-expand-lg" style="background-color:#3b5998;">
      <a class="navbar-brand" href="#" style="color:white;font-size:35px;margin-left:150px;">Facebook</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav" style="margin-left:600px;">
        <ul class="navbar-nav">
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Profile", user_path(current_user.id), class:"nav-link", style:"color:white;" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", session_path(current_user.id), method: :delete, class:"nav-link", style:"color:white;" %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Sign up", new_user_path, class:"nav-link", style:"color:white;" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_session_path,class:"nav-link", style:"color:white;" %>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>
        <%= yield %>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row" style="margin-left:400px;">
      <div class="col-md-6">
          <div class="form-group">
            <%= form.label :image %><br>
            <%= image_tag(@post.image.url,class:"imageupload" ) if @post.image && @post.image.url %>
            <%= form.file_field :image %>
            <%= form.hidden_field :image_cache %>
          </div>
          <div class="form-group">
            <%= form.label :content %>
            <%= form.text_area :content, class:"form-control", id:"exampleFormControlTextarea1", rows:'3' %>
          </div>
          <div class="form-group">
            <%= form.hidden_field :user_id, value: current_user.id %>
          </div>
          <%= form.submit class:"btn btn-primary" %>
          <%= link_to 'Back', posts_path, class:"btn" %>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/comfirm.html.erb
<h1>confirmation screen</h1>
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <!-- Description for displaying the uploaded image on the confirmation screen -->
  <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Post" %>
<% end %>

<%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Return", name: "back" %>
<% end %>

app/views/posts/edit.html.erb
<h1 style="text-align:center;">Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<% @posts.each do |post| %>
<center>
<div class="card text-center" style="width:900px;border-radius:30px;">
  <div class="card-header">
    <strong><%= post.user.first_name %>s'Post</strong>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= image_tag post.image.url, class:"imageupload" %></h5>
    <strong>Content</strong><p class="card-text"><%= post.content %></p>
    <strong>UserName</strong><p class="card-text"><%= post.user.first_name %></p>
    <%= link_to 'Show', post, class:"btn btn-success" %>
    <%= link_to 'Edit', edit_post_path(post), class:"btn btn-primary" %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
  </div>
</div><br>
<% end %>
<%= link_to 'New Post', new_post_path, class:"btn btn-warning" %>
<br>
</center>

app/views/posts/new.html.erb
<h1 style="text-align:center;">New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card text-center" style="width:900px;border-radius:30px;margin-left:150px;">
  <div class="card-header">
    <strong><%= @post.user.first_name %>s'Post</strong>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= image_tag @post.image.url, class:"imageupload" %></h5>
    <strong>Content</strong><p class="card-text"><%= @post.content %></p>
    <strong>UserName</strong><p class="card-text"><%= @post.user.first_name %></p>
    <%= link_to 'Comfirm Post', posts_path, data: { confirm: 'Are you sure do you want to Comfirm?' }, class:"btn btn-primary" %>
    <%= link_to 'Back', edit_post_path(@post), class:"btn" %>
  </div>
</div><br>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
      <div class="container">
      <div class=row>
      <div class="col-md-6" style="margin-left:600px;;">
        <h1 style="font-size:30px;">Create a New Account</h1>
        <p>It’s quick and easy.</p>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= form.text_field :first_name, class:"form-control", id:"inputEmail4", placeholder:"First Name" %>
          </div>
          <div class="form-group col-md-6">
            <%= form.text_field :last_name, class:"form-control", id:"inputEmail4", placeholder:"Last Name" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.text_field :phone_number,class:"form-control", id:"inputAddress", placeholder:"Phone Number" %>
        </div>
        <div class="form-group">
          <%= form.text_field :email, class:"form-control", id:"inputAddress2", placeholder:"Email" %>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= form.text_field :password, class:"form-control", id:"inputCity", placeholder:"New Password" %>
          </div>
        <div class="form-group col-md-6">
          <%= form.text_field :password_comfirm, class:"form-control", id:"inputCity", placeholder:"Password Confirmation" %>
        </div>
        </div>
        <div class="form-group">
          <%= form.label :dob %><br>
          <%= form.date_select :dob, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= form.text_field :sex, class:"form-control", placeholder:"Gender" %>
        </div>
        <%= form.submit class:"btn btn-primary" %>
        <%= link_to 'Back', users_path, class:"btn" %>
      </div>
      </div>
      </div>
    <% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align:center;">Users</h1>

<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Phone number</th>
      <th scope="col">Email</th>
      <th scope="col">Password digest</th>
      <th scope="col">Password comfirm</th>
      <th scope="col">Dob</th>
      <th scope="col">Sex</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_comfirm %></td>
        <td><%= user.dob %></td>
        <td><%= user.sex %></td>
        <td><%= link_to 'Show', user, class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Password digest:</strong>
  <%= @user.password %>
</p>
<p>
  <strong>Password comfirm:</strong>
  <%= @user.password_comfirm %>
</p>
<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>
<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>
<center>
<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-warning" %>
<%= link_to 'Back', users_path, class:"btn" %>